---
- name: Get facts for network interfaces for {{ az_scope }}
  azure_rm_networkinterface_info:
    resource_group: "{{ az_resourcegroup_name }}"
    name: "nic-{{ az_scope }}-{{ item }}"
  with_sequence: count="{{az_count}}" 
  register: nics

- debug:
    var: nics

# - name: Get list of EAP IP address to Add 
#   vars:
    # ip_query: 'results[*].ansible_facts.azure_networkinterfaces[0].properties.ipConfigurations[*].properties.privateIPAddress'
#     ips_to_add_eap: "{{ nics | json_query(ip_query) }}"
#   set_fact:  
#     ips_to_add_eap: "{{ ips_to_add_eap.0 }}"
#   when: az_scope == 'eap'

# - name: Add EAP hosts to in memory inventory
#   add_host:
#     name: "{{ item }}"
#     groups: "{{ az_scope }}"
#   with_items: "{{ ips_to_add_eap }}"
#   when: az_scope == 'eap'

- name: Get list of IP address to Add for {{ az_scope }}
  #vars:
    #ip_query: 'results[0].networkinterfaces[0].ip_configurations[0].privateIPAddress'
    #ip_query_result: "{{ nics | json_query(ip_query) }}"
  set_fact:  
    ips_to_add: "{{ nics.results[0].networkinterfaces[0].ip_configurations[0].privateIPAddress }}"
  
- debug: 
    var: ips_to_add

- name: Add {{ az_scope }} hosts to in memory inventory
  add_host:
    name: "{{ item }}"
    groups: "{{ az_scope }}"
  with_items: "{{ ips_to_add }}"

- name: Wait for SSH to come up
  wait_for_connection:
    timeout: 600
    sleep: 15
  delegate_to: "{{ item }}"
  with_items: "{{ ips_to_add }}"

# - name: Wait for SSH to come up
#   wait_for_connection:
#     timeout: 600
#     sleep: 15
#   delegate_to: "{{ item }}"
#   with_items: "{{ ips_to_add_eap }}"
#   when: az_scope == 'eap'

# Sometimes I need to use this role to create public IP VMs
# Todo: add a role variable to control this

# - name: Get the public ip address
#   azure_rm_publicipaddress:
#     resource_group: "{{ az_resourcegroup_name }}"
#     name:  "{{ az_scope }}-{{ item }}-public"
#     allocation_method: Dynamic
#   with_sequence: count="{{az_count}}" 
#   register: public_ip

# - debug: 
#     var: item.state.ip_address
#   with_items: "{{ public_ip.results }}"

# - name: Add hosts to in memory inventory
#   add_host:
#     name: "{{ item.state.ip_address }}"
#     groups: "{{ az_scope }}"
#   with_items: "{{ public_ip.results }}"

# - name: Wait for SSH to come up
#   wait_for_connection:
#     timeout: 600
#     sleep: 15
#   delegate_to: "{{ item.state.ip_address }}"
#   with_items: "{{ public_ip.results }}"


